---
sudo: required
dist: trusty

language: python
python: "2.7"

# Doc: https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix
env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.2.2.0
 
branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install nmap
  - sudo apt-get install systemd

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

script:
  # Check the role/playbook's syntax.
  - CURR_PWD=$(pwd) 
  - ANSIBLE_ROLES_PATH=$(dirname $CURR_PWD)
  - echo $ANSIBLE_ROLES_PATH is ANSIBLE_ROLES_PATH
  - cd  tests; ansible-playbook -i inventory test.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  - ls -ltr ; bash -x ./test.sh

  
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
